[template]
cargo_generate_version = "0.10.0"
ignore = [
    "target",
    "Cargo.lock",
]
exclude = [
    ".vscode/.cortex-debug.peripherals.state.json",
    ".vscode/.cortex-debug.registers.state.json",
]

[hooks]
pre = [
    "target-selection.rhai",
    "cleanup.rhai",
]
