## references:
# cache: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
# "needs": https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds

name: build app template
on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - "**/docs/**"
      - "**.md"
#  pull_request:
#    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: check templates
#    strategy:
#      fail-fast: false
#      matrix:
#        version: [ 'macos-latest', 'ubuntu-latest', 'windows-latest']
#    runs-on: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: setup | rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
#          components: clippy, rustfmt
      - name: setup | cargo-generate
        run: cargo install cargo-generate
      - uses: Swatinem/rust-cache@v1
